@extends('layouts.app')
@section('title',$brand->exists?'Edit application':'Add application')
@section('content')
<div class="page-heading"><div><a class="back" href="{{ route('applications') }}">← Applications</a><h1>{{ $brand->exists?'Shape your application.':'Give your brand a home.' }}</h1><p class="muted">These details guide the content you create for this application.</p></div></div>
<form class="panel form-panel" method="post" action="{{ $brand->exists?route('applications.update',$brand):route('applications.store') }}">@csrf @if($brand->exists) @method('PUT') @endif
<div class="form-section"><h2>The essentials</h2><div class="form-grid"><label>Application name <span>*</span><input name="name" maxlength="150" required value="{{ old('name',$brand->name) }}" placeholder="Your product or organization"></label><label>Website<input name="website" type="url" maxlength="2048" value="{{ old('website',$brand->website) }}" placeholder="https://your-website.com"></label></div><label>Description<textarea name="description" rows="3" maxlength="5000" placeholder="What does your application do?">{{ old('description',$brand->description) }}</textarea></label></div>
<div class="form-section"><h2>Audience & voice</h2><label>Target audience<textarea name="audience" rows="2" maxlength="2000" placeholder="Who are you trying to reach?">{{ old('audience',$brand->audience) }}</textarea></label><div class="form-grid"><label>Tone <span>*</span><input name="tone" required maxlength="150" value="{{ old('tone',$brand->tone??'Helpful and clear') }}"></label><label>Language <span>*</span><input name="language" list="content-languages" required maxlength="100" value="{{ old('language',$brand->language??'English') }}"></label></div><label>Content instructions<textarea name="instructions" rows="4" maxlength="10000" placeholder="Topics to cover, preferred style, facts to include or claims to avoid…">{{ old('instructions',$brand->instructions) }}</textarea></label></div>
<div class="form-section"><h2>Publishing requirements</h2><input type="hidden" name="pyp_only" value="0"><label class="checkbox"><input type="checkbox" name="pyp_only" value="1" @checked(old('pyp_only',$brand->pyp_only))>Publish only previous-year exam questions</label><p class="muted">Requires a question card, exam, year, paper source and confirmed provenance on every platform. Unverified practice questions remain drafts.</p></div>
<div class="form-section"><h2>AI preference <span class="pill">Optional</span></h2><p class="muted">Choose a provider for this application, or decide later. You can override it for each AI request.</p><label>Preferred provider<select name="ai_connection_id"><option value="">Decide later</option>@foreach($connections as $connection)<option value="{{ $connection->id }}" @selected(old('ai_connection_id',$brand->ai_connection_id)==$connection->id)>{{ \App\Models\AiConnection::PROVIDERS[$connection->provider] }}{{ $connection->model?' · '.$connection->model:'' }}</option>@endforeach</select></label></div>
<div class="form-section"><h2>Image & video preferences</h2><p><a href="{{ route('media.settings') }}">Configure media providers and separate budgets</a></p>
@foreach(['image'=>'Image provider','video'=>'Video provider'] as $kind=>$label)
<label>{{ $label }}<select name="{{ $kind }}_connection_id"><option value="">Decide later</option>@foreach($mediaConnections->where('kind',$kind) as $mediaConnection)<option value="{{ $mediaConnection->id }}" @selected(old($kind.'_connection_id',$brand->{$kind.'_connection_id'})==$mediaConnection->id)>Google {{ $kind==='image'?'Gemini':'Veo' }} · {{ $mediaConnection->model }}</option>@endforeach</select></label>
@endforeach</div>
<div class="actions"><a class="button secondary" href="{{ route('applications') }}">Cancel</a><button class="button">Save application</button></div></form><datalist id="content-languages"><option value="English">English</option><option value="Hindi">हिन्दी (Hindi)</option></datalist>
@endsection
