@extends('layouts.app')
@section('title','Overview')
@section('content')
<div class="page-heading"><div><div class="eyebrow">YOUR PUBLISHING WORKSPACE</div><h1>A home for every story.</h1><p class="muted">Bring your applications together. Give each one its own voice.</p></div><a class="button" href="{{ route('posts.create') }}">＋ Create a post</a></div>
<div class="stats"><div class="stat"><span>Applications</span><strong>{{ $brands->count() }}</strong><small>Your brands, in one place</small></div><div class="stat"><span>Content library</span><strong>{{ $brands->sum('posts_count') }}</strong><small>Drafts, reviewed and published posts</small></div><div class="stat"><span>Social accounts saved</span><strong>{{ $savedAccounts }}</strong><small><a href="{{ route('social') }}">Manage setup · {{ $connectedPages }} Facebook Pages verified →</a></small></div></div>
<div class="hero"><div><div class="eyebrow">START WITH YOUR APPLICATION</div><h2>Different brands.<br>One clear workflow.</h2><p>Set the audience, voice and content direction for any application. No code integration required.</p><a class="button light" href="{{ route('applications.create') }}">Add an application ↗</a></div><div class="flow-visual" aria-label="Application to draft to review"><div class="flow-node">▦ <span>Your application</span><small>Audience · voice · purpose</small></div><span class="connector">↓</span><div class="flow-node">✎ <span>Create a draft</span><small>Shape your next post</small></div><span class="connector">↓</span><div class="flow-node final">✓ <span>Ready for review</span></div></div></div>
<div class="section-heading"><h2>Application health</h2><a href="{{ route('monitoring') }}">Manage monitoring →</a></div>
<div class="monitor-summary">@forelse($brands as $brand)<a href="{{ $brand->healthMonitor?route('monitoring.show',$brand->healthMonitor):route('monitoring') }}">{{ $brand->name }} <span class="badge {{ $brand->healthMonitor?->displayStatus() }}">{{ ucfirst($brand->healthMonitor?->displayStatus() ?? 'Not configured') }}</span></a>@empty<p class="muted">Add an application to configure its health checks.</p>@endforelse</div>
<div class="section-heading"><h2>Recent content</h2><a href="{{ route('posts') }}">View all posts →</a></div>
@if($posts->isEmpty())<div class="empty panel"><span class="empty-icon">▤</span><h3>Your next story starts here.</h3><p>Create an application, then save your first draft.</p><a class="text-link" href="{{ $brands->isEmpty()?route('applications.create'):route('posts.create') }}">{{ $brands->isEmpty()?'Add your first application':'Write your first post' }} →</a></div>
@else<div class="panel">@foreach($posts as $post)<a class="post-row" href="{{ route('posts.edit',$post) }}"><div class="post-icon">▤</div><div class="grow"><strong>{{ $post->title }}</strong><small>{{ $post->brand->name }} · {{ \App\Models\Post::CHANNELS[$post->channel] }}</small></div><span class="badge {{ $post->status }}">{{ ucfirst($post->status) }}</span><span class="row-arrow">↗</span></a>@endforeach</div>@endif
@endsection
